apiVersion: v1
kind: Pod
metadata:
  name: guestbook
spec:
  containers:
  - name: redis
    image: redis
  - name: guestbook
    image: google/guestbook-python-redis
    ports:
    - name: www
      containerPort: 80
      hostPort: 80
    volumeMounts:
      - mountPath: /hosttmp
        name: data
  volumes:
    - name: data
      hostPath:
        path: /tmp
